import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner/banner'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>coffee corner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText={"View stores nearby.."} />
        <div className={styles.heroImage} >
          <Image src="/static/Hero-image.png" width={700} height={400} priority= {true} />
        </div>
      </main>  
    </div>
  )
}
